[package]
name = "ezwordle"
authors = ["Hobbs Bros."]
license = "MIT"
description = "A simple bot to help you solve the daily Wordle."
repository = "https://github.com/hobbsbros/ezwordle"
version = "0.4.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.16.2"

[[bin]]
name = "ezwordle"
path = "src/wordler.rs"

[[bin]]
name = "benchmark"
path = "src/benchmark.rs"

[lib]
name = "util"
path = "src/util/mod.rs"